# SIMULATION CONFIGURATIONS #
LAMBDA = 0.1
SLOTS = 1000
USERS_COUNT = 100

# CHANNEL CONFIGURATIONS #
CHANNELS = 10  # if > 1 => multichannel

# USER CONFIGURATIONS #
SLOT_INTERVAL = 1
P_dtp = 0.5

# CHANNEL RESPONSE AT THE END OF THE SLOT #
RESPONSE_EMPTY = 0
RESPONSE_OK = 1
RESPONSE_CONFLICT = 2
